# Generated by Django 5.2.3 on 2025-07-01 05:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='is_public',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='is_redacted',
            new_name='redacted',
        ),
        migrations.AddField(
            model_name='quote',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quote',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='quotes_participating', to=settings.AUTH_USER_MODEL),
        ),
    ]
