# Generated by Django 5.2.3 on 2025-07-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_rename_is_public_quote_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='refused',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='signature',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
