# Generated by Django 5.2.3 on 2025-07-02 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_signature_refused_alter_signature_signature_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants_signatures', to='quotes.quote'),
        ),
    ]
