# Generated by Django 5.2.3 on 2025-07-02 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_alter_signature_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='quotes.quote'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='signed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
