# Generated by Django 5.2.3 on 2025-07-08 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_accountrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountrequest',
            name='processed',
        ),
    ]
