# Generated by Django 5.2.3 on 2025-07-10 04:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_quote_approved_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='flagged_by',
            field=models.ManyToManyField(blank=True, related_name='flagged_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quote',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
