# Generated by Django 5.2.3 on 2025-07-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0012_quoterankvote_voted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_source',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_source_image',
            field=models.ImageField(blank=True, null=True, upload_to='quote_sources/'),
        ),
    ]
